/**
 * The full Unicode emoji set, loaded on demand.
 *
 * `emoji-data.json` is generated by scripts/build-emoji-data.mjs from Emojibase
 * — every emoji Unicode defines, every skin tone, and the shortcodes Slack,
 * GitHub, Discord and JoyPixels use for each. It is ~60 KB gzipped, so it is a
 * separate chunk fetched the first time a picker opens or a `:shortcode:`
 * needs resolving, never part of the first paint.
 */

export interface EmojiEntry {
  unicode: string;
  label: string;
  group: number;
  keywords: string;
  shortcodes: string[];
  skins?: string[];
}

export interface EmojiIndex {
  list: EmojiEntry[];
  byGroup: EmojiEntry[][];
  /** Every shortcode any supported app uses → the emoji. */
  byShortcode: Map<string, EmojiEntry>;
}

type Row = [string, string, number, string, string[], string[]?];

/** Emojibase group ids in picker order (2, "component", is dropped at build). */
export const EMOJI_GROUPS = [0, 1, 3, 4, 5, 6, 7, 8, 9] as const;
export type EmojiGroupId = (typeof EMOJI_GROUPS)[number];

let index: EmojiIndex | null = null;
let pending: Promise<EmojiIndex> | null = null;

export function getLoadedEmojiIndex(): EmojiIndex | null {
  return index;
}

export function loadEmojiIndex(): Promise<EmojiIndex> {
  if (index) return Promise.resolve(index);
  if (!pending) {
    pending = import('./emoji-data.json')
      .then((mod) => {
        const rows = ((mod as { default?: unknown }).default ?? mod) as Row[];
        const list: EmojiEntry[] = rows.map(([unicode, label, group, keywords, shortcodes, skins]) => ({
          unicode, label, group, keywords, shortcodes, skins,
        }));
        const byGroup: EmojiEntry[][] = [];
        const byShortcode = new Map<string, EmojiEntry>();
        for (const e of list) {
          (byGroup[e.group] ||= []).push(e);
          for (const code of e.shortcodes) if (!byShortcode.has(code)) byShortcode.set(code, e);
        }
        index = { list, byGroup, byShortcode };
        return index;
      })
      .catch((err) => {
        pending = null;
        throw err;
      });
  }
  return pending;
}

export function searchEmoji(idx: EmojiIndex, query: string, limit = 200): EmojiEntry[] {
  const q = query.trim().toLowerCase().replace(/^:|:$/g, '');
  if (!q) return [];
  const starts: EmojiEntry[] = [];
  const contains: EmojiEntry[] = [];
  for (const e of idx.list) {
    if (e.shortcodes.some((c) => c.startsWith(q)) || e.label.toLowerCase().startsWith(q)) starts.push(e);
    else if (e.label.toLowerCase().includes(q) || e.keywords.includes(q) || e.shortcodes.some((c) => c.includes(q))) contains.push(e);
    if (starts.length >= limit) break;
  }
  return starts.concat(contains).slice(0, limit);
}

/** Skin tone modifiers, index 0 = none. Stored per device like any picker. */
export const SKIN_TONES = ['', '🏻', '🏼', '🏽', '🏾', '🏿'] as const;

export function withSkinTone(e: EmojiEntry, tone: number): string {
  if (!tone || !e.skins?.length) return e.unicode;
  // Multi-person emoji carry every tone pairing (🧑🏻‍🤝‍🧑🏿 …); the preferred
  // tone applies the uniform one, where every modifier is the chosen tone.
  const mod = SKIN_TONES[tone];
  return (
    e.skins.find((s) => {
      const mods = s.match(/[\u{1F3FB}-\u{1F3FF}]/gu);
      return !!mods && mods.every((m) => m === mod);
    }) ?? e.unicode
  );
}
