/**
 * Emoji picker data: the full Unicode set, keyword search in the viewer's
 * language, skin tones, recents and per-device support detection.
 *
 * The dataset is generated by scripts/build-emoji-data.mjs — never edit the
 * JSON by hand. emoji.json (~12 KB gzipped) is a lazy chunk loaded the first
 * time a picker opens; keyword files are fetched from the versioned public path
 * so only the viewer's language is ever downloaded.
 */

export type EmojiGroup =
  | 'smileys'
  | 'people'
  | 'animals'
  | 'food'
  | 'travel'
  | 'activities'
  | 'objects'
  | 'symbols'
  | 'flags';

export interface EmojiEntry {
  /** Index into the dataset (and into every keyword file). */
  i: number;
  char: string;
  group: EmojiGroup;
  /** Unicode Emoji version ×10. */
  v: number;
  /** Light → dark skin-tone variants, when the emoji takes one. */
  skins?: string[];
  skinV?: number;
  /** Noto animated codepoint, when Google publishes an animated version. */
  anim?: string;
}

export interface EmojiDataset {
  version: string;
  groups: EmojiGroup[];
  entries: EmojiEntry[];
  byChar: Map<string, EmojiEntry>;
  /** Locale → keyword file name. */
  locales: Record<string, string>;
}

export interface EmojiKeywords {
  labels: string[];
  search: string[];
}

type RawRow = [string, number, number, string[]?, number?];
interface RawDataset {
  version: string;
  groups: EmojiGroup[];
  emoji: RawRow[];
  animated: Record<string, string>;
}

/**
 * The picks row every picker opens on. What people here actually send —
 * markets, memes, respect — ahead of the Unicode groups.
 */
export const DEHUB_PICKS = [
  '🚀', '💎', '🙌', '🔥', '💯', '🫡', '👀', '🤝',
  '🧠', '🌕', '📈', '📉', '🐂', '🐻', '🐋', '🦍',
  '💰', '🪙', '🤑', '🏆', '👑', '⚡', '🎯', '🔫',
  '🎮', '🎬', '🫶', '😤', '💀', '🤡', '🗿', '🥶',
];

let datasetPromise: Promise<EmojiDataset> | null = null;

export function loadEmojiData(): Promise<EmojiDataset> {
  datasetPromise ??= Promise.all([import('./data/emoji.json'), import('./data/locales.json')])
    .then(([rawMod, locMod]) => {
      const raw = (rawMod.default ?? rawMod) as unknown as RawDataset;
      const locales = (locMod.default ?? locMod) as unknown as Record<string, string>;
      const entries: EmojiEntry[] = raw.emoji.map(([char, g, v, skins, skinV], i) => ({
        i,
        char,
        group: raw.groups[g],
        v,
        skins,
        skinV: skins ? skinV ?? v : undefined,
        anim: raw.animated[i],
      }));
      const byChar = new Map<string, EmojiEntry>();
      for (const e of entries) {
        byChar.set(e.char, e);
        // Pickers and chat history hold the FE0F-less form of some emoji too.
        byChar.set(e.char.replace(/️/g, ''), e);
      }
      return { version: raw.version, groups: raw.groups, entries, byChar, locales };
    })
    .catch((err) => {
      datasetPromise = null;
      throw err;
    });
  return datasetPromise;
}

const keywordCache = new Map<string, Promise<EmojiKeywords | null>>();

function fetchKeywords(version: string, file: string): Promise<EmojiKeywords | null> {
  const key = `${version}/${file}`;
  let p = keywordCache.get(key);
  if (!p) {
    p = fetch(`/emoji-data/${version}/names/${file}.json`)
      .then((res) => (res.ok ? res.json() : null))
      .then((rows: unknown) => {
        // The SPA catch-all answers a missing file with index.html and a 200,
        // which fails JSON parsing above or lands here as a non-array.
        if (!Array.isArray(rows)) return null;
        const labels: string[] = [];
        const search: string[] = [];
        for (const row of rows as string[]) {
          const bar = row.indexOf('|');
          labels.push(row.slice(0, bar));
          search.push(` ${row.slice(bar + 1)}`);
        }
        return { labels, search };
      })
      .catch(() => null);
    p.then((v) => {
      if (!v) keywordCache.delete(key);
    });
    keywordCache.set(key, p);
  }
  return p;
}

/** Keywords for the viewer's language, plus English, which every locale also searches. */
export async function loadKeywords(
  data: EmojiDataset,
  locale: string,
): Promise<{ local: EmojiKeywords | null; en: EmojiKeywords | null }> {
  const base = locale.toLowerCase().split('-')[0];
  const file = data.locales[locale] ?? data.locales[base];
  const [en, local] = await Promise.all([
    fetchKeywords(data.version, 'en'),
    file && file !== 'en' ? fetchKeywords(data.version, file) : Promise.resolve(null),
  ]);
  return { local, en };
}

/**
 * Every query word has to start one of the emoji's keywords. Ranked: label
 * match, then keyword-start match, then the dataset's own order.
 */
export function searchEmoji(
  query: string,
  entries: EmojiEntry[],
  keywords: Array<EmojiKeywords | null>,
  limit = 240,
): EmojiEntry[] {
  const q = query.trim().toLowerCase().replace(/^:|:$/g, '');
  if (!q) return [];
  const tokens = q.split(/\s+/).map((t) => ` ${t}`);
  const lists = keywords.filter((k): k is EmojiKeywords => !!k);
  const scored: Array<[number, EmojiEntry]> = [];
  for (const e of entries) {
    if (e.char === query.trim()) {
      scored.push([-1, e]);
      continue;
    }
    let best = Infinity;
    for (const k of lists) {
      const hay = k.search[e.i];
      if (!hay || !tokens.every((t) => hay.includes(t))) continue;
      const label = k.labels[e.i]?.toLowerCase() ?? '';
      const score = label === q ? 0 : label.startsWith(q) ? 1 : 2;
      if (score < best) best = score;
    }
    if (best !== Infinity) scored.push([best, e]);
  }
  scored.sort((a, b) => a[0] - b[0] || a[1].i - b[1].i);
  return scored.slice(0, limit).map(([, e]) => e);
}

/** 0 = default yellow, 1-5 = light → dark. */
export type SkinTone = 0 | 1 | 2 | 3 | 4 | 5;
export const SKIN_TONE_SWATCHES = ['✋', '✋🏻', '✋🏼', '✋🏽', '✋🏾', '✋🏿'] as const;

const TONE_KEY = 'dehub:emoji:tone';
const RECENT_KEY = 'dehub:emoji:recent';
const RECENT_MAX = 32;

export function readSkinTone(): SkinTone {
  try {
    const n = Number(localStorage.getItem(TONE_KEY));
    return (n >= 0 && n <= 5 ? n : 0) as SkinTone;
  } catch {
    return 0;
  }
}

export function writeSkinTone(tone: SkinTone) {
  try {
    localStorage.setItem(TONE_KEY, String(tone));
  } catch {
    /* private mode */
  }
}

/** Recents hold the base emoji, so a later tone change re-tints them. */
export function readRecents(): string[] {
  try {
    const raw = JSON.parse(localStorage.getItem(RECENT_KEY) || '[]');
    return Array.isArray(raw) ? raw.filter((s) => typeof s === 'string').slice(0, RECENT_MAX) : [];
  } catch {
    return [];
  }
}

export function pushRecent(base: string): string[] {
  const next = [base, ...readRecents().filter((c) => c !== base)].slice(0, RECENT_MAX);
  try {
    localStorage.setItem(RECENT_KEY, JSON.stringify(next));
  } catch {
    /* private mode */
  }
  return next;
}

/** The emoji to insert for an entry at the chosen tone. */
export function withTone(e: EmojiEntry, tone: SkinTone, maxV: number): string {
  if (!tone || !e.skins || (e.skinV ?? e.v) > maxV) return e.char;
  return e.skins[tone - 1];
}

export function animatedUrl(code: string) {
  return `https://fonts.gstatic.com/s/e/notoemoji/latest/${code}/512.webp`;
}

export interface EmojiSupport {
  /** Newest Unicode Emoji version (×10) this device draws. */
  maxV: number;
  flags: boolean;
}

let supportPromise: Promise<EmojiSupport> | null = null;

/**
 * What this device can actually draw, so the picker never offers tofu.
 *
 * Each Unicode release is probed with one of its own emoji on a canvas: it
 * counts as drawn when it comes out in colour and no wider than a single
 * emoji (an unsupported ZWJ sequence falls apart into two). Windows gets the
 * Noto webfont from index.html, so wait for it to fetch the probe glyphs
 * first — otherwise Segoe's gaps would hide emoji the page can in fact show.
 */
export function detectEmojiSupport(data: EmojiDataset): Promise<EmojiSupport> {
  supportPromise ??= (async () => {
    const fallback: EmojiSupport = { maxV: 1000, flags: true };
    if (typeof document === 'undefined') return fallback;
    const canvas = document.createElement('canvas');
    canvas.width = canvas.height = 32;
    const ctx = canvas.getContext('2d', { willReadFrequently: true });
    if (!ctx) return fallback;

    const probes = new Map<number, string>();
    for (const e of data.entries) {
      if (e.v >= 110 && e.group !== 'flags' && !probes.has(e.v)) probes.set(e.v, e.char);
    }
    const flag = '🇺🇸';
    const stack = `'Apple Color Emoji','Noto Color Emoji','Segoe UI Emoji',sans-serif`;

    try {
      const hasNoto = [...document.fonts].some((f) => f.family.replace(/["']/g, '') === 'Noto Color Emoji');
      if (hasNoto) {
        const text = [...probes.values(), flag].join('');
        await Promise.race([
          document.fonts.load(`20px 'Noto Color Emoji'`, text),
          new Promise((r) => setTimeout(r, 1500)),
        ]);
      }
    } catch {
      /* FontFaceSet missing — probe with what is there */
    }

    ctx.font = `20px ${stack}`;
    ctx.textBaseline = 'top';
    const single = ctx.measureText('😀').width || 20;
    const draws = (ch: string) => {
      if (ctx.measureText(ch).width > single * 1.4) return false;
      ctx.clearRect(0, 0, 32, 32);
      ctx.fillStyle = '#000';
      ctx.fillText(ch, 2, 2);
      const px = ctx.getImageData(0, 0, 32, 32).data;
      for (let i = 0; i < px.length; i += 4) {
        if (px[i + 3] > 0 && (Math.abs(px[i] - px[i + 1]) > 16 || Math.abs(px[i + 1] - px[i + 2]) > 16)) return true;
      }
      return false;
    };

    let maxV = 50;
    for (const v of [...probes.keys()].sort((a, b) => a - b)) {
      if (!draws(probes.get(v)!)) break;
      maxV = v;
    }
    // Every version newer than the last probe that passed stays hidden; a
    // version with no probe of its own rides on the one before it.
    const highest = Math.max(...data.entries.map((e) => e.v));
    if (maxV === Math.max(...probes.keys())) maxV = highest;
    return { maxV, flags: draws(flag) };
  })();
  return supportPromise;
}
