import { describe, expect, it } from "vitest";
import { cloudProjectSession, type CloudProjectLink, type CloudProjectSessionDeps } from "./cloudProjectSession";
import { CloudProjectConflict, type CloudProjectDocument, type CloudProjectMedia } from "./cloudProjectFormat";
import type { CloudDraftCheckpoint, CloudDraftReceipt, CloudDraftRequest, CloudDraftResolution } from "./cloudProjectDraft";
import { videoMattePlan, videoMattePagePlan, validVideoMatte } from "./videoMatte";
import type { MediaClip, ProjectSnapshot } from "./types";

const actor="0x"+"b".repeat(40),owner="0x"+"a".repeat(40),at="2026-10-10T12:00:00Z";
const projectId="aaaaaaaa-1111-4111-8111-111111111111",sourceId="bbbbbbbb-1111-4111-8111-111111111111",writerId="cccccccc-1111-4111-8111-111111111111";
const addedId="dddddddd-1111-4111-8111-111111111111",audioId="eeeeeeee-1111-4111-8111-111111111111";
const copy=<T,>(value:T):T=>JSON.parse(JSON.stringify(value));
function setup(shared=false){
  let serial=0,active=true,guardActive=true,now=Date.parse(at),opened=0,saveCount=0,fail=false,lose=false;
  const sourceOwner=shared?owner:actor;
  const media=(id:string,kind:CloudProjectMedia["kind"]="video",wallet=sourceOwner):CloudProjectMedia=>({id,storagePath:`${wallet}/${id}/source.${kind==="image"?"png":kind==="audio"?"wav":"mp4"}`,name:id,kind,mimeType:kind==="image"?"image/png":kind==="audio"?"audio/wav":"video/mp4",size:10,...(kind==="image"?{}:{duration:20})});
  const base:CloudProjectDocument={version:1,snapshot:{id:projectId,title:"Film",updatedAt:1,
    settings:{width:1920,height:1080,fps:30,aspectPreset:"16:9",background:"#000000"},tracks:[{id:"v",kind:"video",name:"Video",muted:false,hidden:false}],
    clips:[{id:"shot",trackId:"v",kind:"video",mediaId:sourceId,start:0,trimIn:0,duration:5,sourceDuration:20}]},media:[media(sourceId)]};
  let checkpoint:CloudDraftCheckpoint={ownerWallet:sourceOwner,projectId,draftRevision:5,anchorRevision:2,headRevision:2,storedAt:at,document:copy(base)};
  const versions=new Map<number,CloudProjectDocument>([[2,copy(base)]]),requests:CloudDraftRequest[]=[],receipts=new Map<string,CloudDraftReceipt>();
  const local=copy(base.snapshot);local.id="device-project";(local.clips[0] as MediaClip).mediaId="device-source";
  const links=new Map<string,CloudProjectLink>([[local.id,{wallet:actor,projectId,revision:2,media:{"device-source":media(sourceId)},...(shared?{sharedOwner:owner}:{})}]]);
  const uploaded:{id:string;shared?:{owner:string;projectId:string}}[]=[],hydrated:{source:CloudProjectMedia;owner?:string}[]=[],locals:ProjectSnapshot[]=[],loaded:number[]=[];
  let onHydrate:(()=>void)|undefined,onUpload:(()=>void)|undefined,onLoad:(()=>Promise<void>)|undefined;
  let resolution:CloudDraftResolution|undefined;
  const version=async(id:string,revision?:number)=>{loaded.push(revision??checkpoint.headRevision);await onLoad?.();return {projectId:id,revision:revision??checkpoint.headRevision,headRevision:checkpoint.headRevision,savedAt:at,document:copy(versions.get(revision??checkpoint.headRevision)!)};};
  const deps:CloudProjectSessionDeps={wallet:actor,uuid:()=>`${(++serial).toString(16).padStart(8,"0")}-1111-4111-8111-111111111111`,now:()=>now,
    check:()=>{if(!active)throw new Error("Account changed");},readLink:async id=>links.has(id)?copy(links.get(id)!):null,
    writeLink:async(id,value)=>{links.set(id,copy(value));},saveLocal:async value=>{locals.push(copy(value));},
    hydrate:async(source,check,sourceWallet)=>{hydrated.push({source:copy(source),owner:sourceWallet});onHydrate?.();check();},
    upload:async(id,cloudId,check,scope)=>{uploaded.push({id,shared:scope});onUpload?.();check();return media(cloudId,"video",scope?.owner||actor);},
    api:{load:version,save:async(id,_document,revision)=>{saveCount++;return {projectId:id,revision:revision+1,savedAt:at};},restore:async()=>{throw new Error("Unexpected restore");},
      editing:{load:(_owner,id)=>version(id),save:async(_owner,id,_document,revision)=>{saveCount++;return {projectId:id,revision:revision+1,savedAt:at};}},
      review:{load:(_owner,id,revision)=>version(id,revision)},drafts:{
        load:async()=>copy(checkpoint),open:async()=>{opened++;return {writerId,nextSequence:1,expiresAt:new Date(now+3600000).toISOString(),checkpoint:copy(checkpoint)};},
        save:async(_owner,_id,request)=>{
          requests.push(copy(request));
          const pending=links.get(local.id)?.liveDraft?.pending;expect(pending).toEqual(request);
          if(fail)throw new Error("Writer expired or response unavailable");
          const previous=receipts.get(request.requestId);if(previous)return copy(previous);
          if(request.expectedRevision!==checkpoint.draftRevision||request.anchorRevision!==checkpoint.headRevision)throw new CloudProjectConflict("Draft moved");
          const receipt:CloudDraftReceipt={ownerWallet:sourceOwner,projectId,draftRevision:request.expectedRevision+1,anchorRevision:request.anchorRevision,sequence:request.sequence,requestId:request.requestId,storedAt:new Date(now).toISOString()};
          receipts.set(request.requestId,receipt);checkpoint={...checkpoint,draftRevision:receipt.draftRevision,anchorRevision:receipt.anchorRevision,document:copy(request.document)};
          if(lose){lose=false;throw new Error("Response lost");}return copy(receipt);
        },resolve:async()=>resolution||{status:"unknown"},
      }} };
  return {deps,links,local,base,versions,requests,receipts,uploaded,hydrated,locals,loaded,media,sourceOwner,session:()=>cloudProjectSession(deps),
    remote:()=>checkpoint.document,checkpoint:()=>checkpoint,guard:()=>{if(!guardActive)throw new Error("Project changed");},switchProject:()=>{guardActive=false;},resume:()=>{guardActive=true;},switchAccount:()=>{active=false;},
    onHydrate:(run?:()=>void)=>{onHydrate=run;},onUpload:(run?:()=>void)=>{onUpload=run;},onLoad:(run?:()=>Promise<void>)=>{onLoad=run;},
    fail:(value=true)=>{fail=value;},lose:()=>{lose=true;},resolve:(value:CloudDraftResolution)=>{resolution=value;},
    expire:()=>{now+=7200000;},opened:()=>opened,saved:()=>saveCount,
    moveHead:(revision:number,document:CloudProjectDocument)=>{versions.set(revision,copy(document));checkpoint.headRevision=revision;},
    advanceDraft:()=>{checkpoint.draftRevision++;},
    async receive(value=local){let accepted=value;const result=await cloudProjectSession(deps).receiveLiveProject(value,next=>{accepted=next;},()=>{if(!guardActive)throw new Error("Project changed");});return {snapshot:accepted,...result};}};
}

describe("live cloud session with durable links and real outbox",()=>{
  it.each([false,true])("accepts mutable changes without uploading or making permanent history (shared=%s)",async shared=>{const e=setup(shared);e.remote().snapshot.title="Live title";const result=await e.receive();expect(result.snapshot.title).toBe("Live title");expect(result).toMatchObject({changed:true,draftRevision:5,revision:2});expect(e.links.get(e.local.id)?.liveBaseline?.draftRevision).toBe(5);expect(e.uploaded).toEqual([]);expect(e.opened()).toBe(0);expect(e.saved()).toBe(0);expect(e.hydrated[0].owner).toBe(e.sourceOwner);});
  it("combines independent local and mutable edits while keeping device IDs",async()=>{const e=setup();e.local.title="Local title";e.remote().snapshot.clips[0].duration=4;const result=await e.receive();expect(result.snapshot.title).toBe("Local title");expect(result.snapshot.clips[0]).toMatchObject({mediaId:"device-source",duration:4});});
  it("keeps overlapping local edits and refuses to advance the accepted checkpoint",async()=>{const e=setup();e.local.title="Local";e.remote().snapshot.title="Remote";await expect(e.receive()).rejects.toThrow("overlap");expect(e.locals).toEqual([e.local]);expect(e.links.get(e.local.id)?.liveBaseline).toBeUndefined();expect(e.hydrated).toEqual([]);});
  it("avoids a receive-only history step and an outgoing echo for unchanged content",async()=>{const e=setup();e.remote().snapshot.updatedAt=100;const result=await e.receive();expect(result.changed).toBe(false);expect(await e.session().publishLiveProject(result.snapshot,e.guard)).toBe(false);expect(e.requests).toEqual([]);expect(e.opened()).toBe(0);});
  it("does not echo duration facts measured when new sources are received",async()=>{const e=setup();const added={...e.remote().snapshot.clips[0],id:"added",mediaId:addedId,start:5} as MediaClip;delete added.sourceDuration;e.remote().snapshot.clips.push(added);e.remote().media.push(e.media(addedId));const result=await e.receive();expect((result.snapshot.clips[1] as MediaClip).sourceDuration).toBe(20);expect(await e.session().publishLiveProject(result.snapshot,e.guard)).toBe(false);expect(e.requests).toEqual([]);});
  it("requires an accepted baseline before uploading outgoing sources",async()=>{const e=setup();(e.local.clips[0] as MediaClip).mediaId="private-new";await expect(e.session().publishLiveProject(e.local,e.guard)).rejects.toThrow("Receive the live baseline");expect(e.uploaded).toEqual([]);});
  it.each([false,true])("persists the accepted request before sending without advancing Saved history (shared=%s)",async shared=>{const e=setup(shared),received=await e.receive();received.snapshot.title="Outgoing";expect(await e.session().publishLiveProject(received.snapshot,e.guard)).toBe(true);expect(e.requests[0]).toMatchObject({expectedRevision:5,anchorRevision:2,sequence:1});expect(e.links.get(e.local.id)?.revision).toBe(2);expect(e.links.get(e.local.id)?.liveBaseline?.draftRevision).toBe(6);expect(e.links.get(e.local.id)?.liveDraft?.pending).toBeNull();expect(e.saved()).toBe(0);});
  it("persists completed new-source mappings before sending and uses the original owner",async()=>{const e=setup(true),received=await e.receive();(received.snapshot.clips[0] as MediaClip).mediaId="new-device-source";await e.session().publishLiveProject(received.snapshot,e.guard);expect(e.uploaded).toEqual([{id:"new-device-source",shared:{owner,projectId}}]);expect(e.links.get(e.local.id)?.media["new-device-source"].storagePath.startsWith(owner+"/")).toBe(true);expect(e.requests[0].document.media[0].id).toBe(e.links.get(e.local.id)?.media["new-device-source"].id);});
  it("retains a completed mapping if Stop arrives during upload and sends no draft",async()=>{const e=setup(true),received=await e.receive();(received.snapshot.clips[0] as MediaClip).mediaId="new-device-source";e.onUpload(e.switchProject);await expect(e.session().publishLiveProject(received.snapshot,e.guard)).rejects.toThrow("Project changed");expect(e.links.get(e.local.id)?.media["new-device-source"]).toBeDefined();expect(e.requests).toEqual([]);e.onUpload();e.resume();await e.session().publishLiveProject(received.snapshot,e.guard);expect(e.uploaded).toHaveLength(1);});
  it("recovers a lost acknowledgment through a fresh session using its exact nonce",async()=>{const e=setup(),received=await e.receive();received.snapshot.title="Outgoing";e.lose();await expect(e.session().publishLiveProject(received.snapshot,e.guard)).rejects.toThrow("Response lost");const pending=copy(e.links.get(e.local.id)!.liveDraft!.pending!);await e.session().recoverLiveProject(e.local.id,e.guard);expect(e.requests[1]).toEqual(pending);expect(e.links.get(e.local.id)?.liveDraft?.pending).toBeNull();expect(e.links.get(e.local.id)?.liveBaseline?.document.snapshot.title).toBe("Outgoing");expect(e.opened()).toBe(1);});
  it("resolves a committed request after writer expiry without registering again",async()=>{const e=setup(),received=await e.receive();received.snapshot.title="Outgoing";e.lose();await expect(e.session().publishLiveProject(received.snapshot,e.guard)).rejects.toThrow();const pending=e.links.get(e.local.id)!.liveDraft!.pending!;e.expire();e.fail();e.resolve({status:"committed",receipt:e.receipts.get(pending.requestId)!});await e.session().recoverLiveProject(e.local.id,e.guard);expect(e.links.get(e.local.id)?.liveDraft?.pending).toBeNull();expect(e.opened()).toBe(1);});
  it("keeps an unprovable request after receipt expiry and blocks a later replacement",async()=>{const e=setup(),received=await e.receive();received.snapshot.title="Outgoing";e.fail();await expect(e.session().publishLiveProject(received.snapshot,e.guard)).rejects.toThrow();const stored=copy(e.links.get(e.local.id)!);e.expire();await expect(e.session().recoverLiveProject(e.local.id,e.guard)).rejects.toThrow("outcome is unknown");received.snapshot.title="Later";await expect(e.session().publishLiveProject(received.snapshot,e.guard)).rejects.toThrow("pending live edit");expect(e.links.get(e.local.id)).toEqual(stored);expect(e.opened()).toBe(1);});
  it("clears only a server-fenced request while retaining its accepted local baseline",async()=>{const e=setup(),received=await e.receive();received.snapshot.title="Outgoing";e.fail();await expect(e.session().publishLiveProject(received.snapshot,e.guard)).rejects.toThrow();const pending=e.links.get(e.local.id)!.liveDraft!.pending!;e.resolve({status:"fenced",checkpoint:copy(e.checkpoint())});await e.session().recoverLiveProject(e.local.id,e.guard);expect(e.links.get(e.local.id)?.liveDraft).toMatchObject({writer:null,pending:null,lastRequestId:pending.requestId});expect(e.locals[e.locals.length-1].title).toBe("Outgoing");});
  it("renews an expired idle writer against the last accepted draft rather than an unseen counter",async()=>{const e=setup(),received=await e.receive();received.snapshot.title="First";await e.session().publishLiveProject(received.snapshot,e.guard);e.expire();e.advanceDraft();received.snapshot.title="Second";await expect(e.session().publishLiveProject(received.snapshot,e.guard)).rejects.toThrow("Draft moved");expect(e.requests[1]).toMatchObject({expectedRevision:6,anchorRevision:2});expect(e.opened()).toBe(2);expect(e.links.get(e.local.id)?.liveDraft?.pending?.document.snapshot.title).toBe("Second");});
  it("reconciles a mutable draft anchored to older Saved history using exact versions",async()=>{const e=setup(true);e.remote().snapshot.title="Live title";const next=copy(e.base);next.snapshot.clips[0].duration=4;e.moveHead(3,next);const received=await e.receive();expect(received.snapshot.title).toBe("Live title");expect(received.snapshot.clips[0].duration).toBe(4);expect(e.loaded).toContain(2);expect(e.loaded).toContain(3);expect(e.links.get(e.local.id)?.liveBaseline).toMatchObject({anchorRevision:3,headRevision:3,draftRevision:5});expect(e.saved()).toBe(0);});
  it("keeps the draft when old-anchor live edits overlap a newer Saved version",async()=>{const e=setup();e.remote().snapshot.title="Live";const next=copy(e.base);next.snapshot.title="Saved";e.moveHead(3,next);await expect(e.receive()).rejects.toThrow("overlap");expect(e.links.get(e.local.id)?.revision).toBe(2);expect(e.links.get(e.local.id)?.liveBaseline).toBeUndefined();});
  it("hydrates all paged masks and extracted audio under the original private owner",async()=>{const e=setup(true),clip=e.remote().snapshot.clips[0] as MediaClip;clip.duration=12;const plan=videoMattePlan(clip,640,360,20,120);const masks=[addedId,"dddddddd-2222-4222-8222-222222222222","dddddddd-3333-4333-8333-333333333333"];clip.videoMatte={...plan,mediaId:masks[0],pages:masks.map((mediaId,index)=>({...videoMattePagePlan(plan,index),mediaId}))};for(const page of clip.videoMatte.pages!)e.remote().media.push({...e.media(page.mediaId,"image"),width:page.atlasWidth,height:page.atlasHeight});e.remote().snapshot.tracks.push({id:"audio",kind:"audio",name:"Extracted",muted:false,hidden:false});e.remote().snapshot.clips.push({id:"audio-clip",kind:"audio",trackId:"audio",mediaId:audioId,start:0,trimIn:0,duration:5,sourceDuration:20});e.remote().media.push(e.media(audioId,"audio"));const received=await e.receive();expect(validVideoMatte(received.snapshot.clips[0] as MediaClip)).toBe(true);expect(e.hydrated).toHaveLength(5);expect(e.hydrated.every(row=>row.owner===owner)).toBe(true);expect((received.snapshot.clips[0] as MediaClip).videoMatte?.sourceMediaId).toBe("device-source");expect(e.uploaded).toEqual([]);});
  it("retains incoming device IDs after hydration is interrupted",async()=>{const e=setup();e.remote().snapshot.clips.push({...e.remote().snapshot.clips[0],id:"added",mediaId:addedId,start:5} as MediaClip);e.remote().media.push(e.media(addedId));e.onHydrate(e.switchProject);await expect(e.receive()).rejects.toThrow("Project changed");const binding=Object.entries(e.links.get(e.local.id)!.media).find(([,source])=>source.id===addedId)!;e.onHydrate();e.resume();const received=await e.receive();expect((received.snapshot.clips[1] as MediaClip).mediaId).toBe(binding[0]);expect(Object.values(e.links.get(e.local.id)!.media).filter(source=>source.id===addedId)).toHaveLength(1);});
  it("never accepts another wallet's linked draft",async()=>{const e=setup();e.links.get(e.local.id)!.wallet=owner;await expect(e.receive()).rejects.toThrow("Save this project");expect(e.hydrated).toEqual([]);expect(e.locals).toEqual([]);});
  it("rejects a late project change before applying any received edit",async()=>{const e=setup();e.remote().snapshot.title="Remote";e.onHydrate(e.switchProject);await expect(e.receive()).rejects.toThrow("Project changed");expect(e.links.get(e.local.id)?.liveBaseline).toBeUndefined();expect(e.links.get(e.local.id)?.revision).toBe(2);});
  it("uses the same wallet mutex for continuous receive and explicit Save",async()=>{const e=setup();let finish!:()=>void,entered!:()=>void;const ready=new Promise<void>(resolve=>{entered=resolve;});e.onLoad(async()=>{entered();await new Promise<void>(resolve=>{finish=resolve;});});const receiving=e.receive();await ready;await expect(e.session().save(e.local)).rejects.toThrow("already running");e.onLoad();finish();await receiving;expect(e.saved()).toBe(0);});
  it("saves a personal copy without replacing an unknown request or the original project",async()=>{const e=setup(true),received=await e.receive();received.snapshot.title="Unconfirmed";e.fail();await expect(e.session().publishLiveProject(received.snapshot,e.guard)).rejects.toThrow();const original=copy(e.links.get(e.local.id)!);const saved=await e.session().saveLiveProjectCopy(received.snapshot,e.guard);expect(saved.snapshot.id).not.toBe(e.local.id);expect(saved.snapshot.title).toBe("Unconfirmed");expect(e.links.get(e.local.id)).toEqual(original);const own=e.links.get(saved.snapshot.id)!;expect(own.wallet).toBe(actor);expect(own.sharedOwner).toBeUndefined();expect(Object.values(own.media).every(source=>source.storagePath.startsWith(actor+"/"))).toBe(true);expect(e.uploaded.every(row=>row.shared===undefined)).toBe(true);expect(e.saved()).toBe(1);});
});
