import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { useEditorStore } from "@/store/editorStore";
import { cloudDraftEditorStore } from "./cloudDraftEditorStore";
import { cloudDraftController, type CloudDraftControllerState, type CloudLiveSession } from "./cloudDraftController";
import type { MediaClip, ProjectSnapshot } from "./types";
const wallet="0x"+"a".repeat(40);
const fixture=():ProjectSnapshot=>({id:"device",title:"Film",updatedAt:1,settings:{width:1920,height:1080,fps:30,aspectPreset:"16:9",background:"#000"},tracks:[{id:"v",kind:"video",name:"Video",muted:false,hidden:false}],
  clips:[{id:"a",kind:"video",trackId:"v",mediaId:"source",start:0,trimIn:0,duration:5},{id:"b",kind:"video",trackId:"v",mediaId:"source",start:5,trimIn:0,duration:5}]});
const copy=<T,>(value:T):T=>JSON.parse(JSON.stringify(value));
const controllers:ReturnType<typeof cloudDraftController>[]=[];
beforeEach(()=>{vi.useFakeTimers();useEditorStore.getState().loadSnapshot(fixture());});afterEach(()=>{for(const controller of controllers.splice(0))controller.stop();vi.useRealTimers();});
async function tick(ms=0){vi.advanceTimersByTime(ms);for(let i=0;i<40;i++)await Promise.resolve();}
function setup(){const states:CloudDraftControllerState[]=[];const session:CloudLiveSession={recoverLiveProject:vi.fn(async()=>{}),receiveLiveProject:vi.fn(async(_snapshot,_accept,check)=>{check();}),publishLiveProject:vi.fn(async(_snapshot,check)=>{check();return true;})};const controller=cloudDraftController(wallet,"device",session,cloudDraftEditorStore,{check:()=>{},update:state=>states.push(state)});controllers.push(controller);return {controller,session,states};}
describe("live controller using the actual web history adapter",()=>{
  it("waits for canvas gesture settlement and publishes one latest edit",async()=>{const e=setup(),store=useEditorStore.getState();e.controller.start(true);await tick();const lease=store.beginGesture();store.patchClipLive("a",{start:1});store.patchClipLive("a",{start:2});await tick(5000);expect(e.session.publishLiveProject).toHaveBeenCalledTimes(1);lease.release();await tick(700);expect(e.session.publishLiveProject).toHaveBeenCalledTimes(2);expect(vi.mocked(e.session.publishLiveProject).mock.calls[1][0].clips[0].start).toBe(2);expect(useEditorStore.getState().past).toHaveLength(1);});
  it("holds async commands until the real Undo batch releases",async()=>{const e=setup(),store=useEditorStore.getState();e.controller.start(true);await tick();let finish!:()=>void;const operation=store.runAsOneStep(()=>new Promise<void>(resolve=>{finish=resolve;}));store.updateMediaClip("a",{start:1});store.updateMediaClip("a",{start:2});await tick(5000);expect(e.session.publishLiveProject).toHaveBeenCalledTimes(1);finish();await operation;await tick(700);expect(e.session.publishLiveProject).toHaveBeenCalledTimes(2);expect(useEditorStore.getState().past).toHaveLength(1);});
  it("rebases incoming edits across actual Undo and Redo without adding a step",async()=>{const e=setup(),store=useEditorStore.getState();store.updateMediaClip("a",{audio:{volume:.5}});store.updateMediaClip("a",{audio:{volume:.8}});store.undo();store.selectClip("a");store.setCurrentTime(3);vi.mocked(e.session.receiveLiveProject).mockImplementationOnce(async(snapshot,accept,check)=>{check();const incoming=copy(snapshot);incoming.clips[1].duration=4;accept(incoming);});e.controller.start(false);await tick();expect(useEditorStore.getState().past).toHaveLength(1);expect(useEditorStore.getState().future).toHaveLength(1);expect(useEditorStore.getState().selectedClipIds).toEqual(["a"]);expect(useEditorStore.getState().currentTime).toBe(3);store.redo();expect((useEditorStore.getState().clips[0] as MediaClip).audio?.volume).toBe(.8);store.undo();store.undo();expect((useEditorStore.getState().clips[0] as MediaClip).audio).toBeUndefined();expect(useEditorStore.getState().clips[1].duration).toBe(4);expect(e.session.publishLiveProject).not.toHaveBeenCalled();});
  it("stops on a same-ID load and does not adopt new workspace sharing consent",async()=>{const e=setup();e.controller.start(true);useEditorStore.getState().loadSnapshot(fixture());await tick(5000);expect(e.session.receiveLiveProject).not.toHaveBeenCalled();expect(e.states[e.states.length-1].mode).toBeNull();});
  it("ignores selection, playhead and playback updates",async()=>{const e=setup(),store=useEditorStore.getState();e.controller.start(true);await tick();store.selectClip("a");store.setCurrentTime(2);store.setIsPlaying(true);await tick(5000);expect(e.session.publishLiveProject).toHaveBeenCalledTimes(1);expect(vi.getTimerCount()).toBe(0);});
});
