import { describe, expect, it, vi } from "vitest";
import { cloudDraftController, type CloudDraftControllerState, type CloudLiveSession } from "./cloudDraftController";
import { CloudProjectConflict } from "./cloudProjectFormat";
import { withCloudProjectTransfer } from "./cloudProjectTransfer";
import type { ProjectSnapshot } from "./types";

const wallet="0x"+"a".repeat(40);
const copy=<T,>(value:T):T=>JSON.parse(JSON.stringify(value));
const snapshot=():ProjectSnapshot=>({id:"device",title:"Film",updatedAt:1,
  settings:{width:1920,height:1080,fps:30,aspectPreset:"16:9",background:"#000"},tracks:[],clips:[]});
const settle=async()=>{for(let i=0;i<40;i++)await Promise.resolve();};
function setup(){
  let current=snapshot(),editing=false,scope=0,active=true,serial=0;
  const observers=new Set<()=>void>(),jobs=new Map<number,()=>void>(),states:CloudDraftControllerState[]=[],accepted:ProjectSnapshot[]=[];
  const signal=()=>{for(const observer of [...observers])observer();};
  const session:CloudLiveSession={recoverLiveProject:vi.fn(async(_id,check)=>{check();}),
    receiveLiveProject:vi.fn(async(_snapshot,_accept,check)=>{check();}),publishLiveProject:vi.fn(async(_snapshot,check)=>{check();return true;})};
  const controller=cloudDraftController(wallet,current.id,session,{scope:()=>scope,current:()=>current,isEditing:()=>editing,
    subscribe:run=>{observers.add(run);return ()=>{observers.delete(run);};},receive:next=>{current=copy(next);accepted.push(copy(next));signal();}},
    {check:()=>{if(!active)throw new Error("Account changed");},update:state=>states.push(state),delay:run=>{const id=++serial;jobs.set(id,run);return ()=>{jobs.delete(id);};}});
  return {controller,session,accepted,states,jobs,observers,current:()=>current,
    edit:(title:string)=>{current={...current,title};signal();},gesture:(value:boolean)=>{editing=value;signal();},
    reset:()=>{scope++;current=snapshot();signal();},switchProject:()=>{current={...current,id:"other"};signal();},switchAccount:()=>{active=false;},
    async flush(){const pending=[...jobs.values()];jobs.clear();for(const run of pending)run();await settle();},
    last:()=>states[states.length-1]};
}

describe("explicit continuous draft delivery",()=>{
  it("does no transfer, registration or timer work before consent",async()=>{const e=setup();e.edit("Private");e.controller.remote(2,7);await e.flush();expect(e.session.recoverLiveProject).not.toHaveBeenCalled();expect(e.session.receiveLiveProject).not.toHaveBeenCalled();expect(e.session.publishLiveProject).not.toHaveBeenCalled();expect(e.jobs.size).toBe(0);});
  it("receives without publishing and stays idle between metadata events",async()=>{const e=setup();e.controller.start(false);await e.flush();expect(e.session.receiveLiveProject).toHaveBeenCalledTimes(1);expect(e.session.publishLiveProject).not.toHaveBeenCalled();expect(e.jobs.size).toBe(0);e.edit("Local");await e.flush();expect(e.session.receiveLiveProject).toHaveBeenCalledTimes(1);e.controller.stop();});
  it("coalesces settled changes into the latest outgoing snapshot",async()=>{const e=setup();e.controller.start(true);await e.flush();e.edit("One");e.edit("Two");e.edit("Three");expect(e.jobs.size).toBe(1);await e.flush();expect(e.session.publishLiveProject).toHaveBeenCalledTimes(2);expect(vi.mocked(e.session.publishLiveProject).mock.calls[1][0].title).toBe("Three");expect(e.jobs.size).toBe(0);e.controller.stop();});
  it("waits without polling until a gesture releases",async()=>{const e=setup();e.gesture(true);e.controller.start(true);e.edit("Drag");await e.flush();expect(e.jobs.size).toBe(0);expect(e.session.receiveLiveProject).not.toHaveBeenCalled();expect(e.last().status).toBe("waiting");e.gesture(false);await e.flush();expect(e.session.publishLiveProject).toHaveBeenCalledTimes(1);e.controller.stop();});
  it("deduplicates saved and mutable counters independently",async()=>{const e=setup();e.controller.start(false);await e.flush();e.controller.remote(1,0);await e.flush();e.controller.remote(1,0);await e.flush();expect(e.session.receiveLiveProject).toHaveBeenCalledTimes(2);e.controller.remote(1,1);await e.flush();expect(e.session.receiveLiveProject).toHaveBeenCalledTimes(3);e.controller.stop();});
  it("Stop removes subscriptions and pending callbacks",async()=>{const e=setup();e.controller.start(true);e.controller.stop();e.edit("Later");e.controller.remote(9,9);await e.flush();expect(e.jobs.size).toBe(0);expect(e.observers.size).toBe(0);expect(e.session.receiveLiveProject).not.toHaveBeenCalled();expect(e.last().mode).toBeNull();});
  it("rejects an incoming result that finishes after Stop",async()=>{const e=setup();let finish!:()=>void;vi.mocked(e.session.receiveLiveProject).mockImplementation(async(value,accept,check)=>{await new Promise<void>(resolve=>{finish=resolve;});check();accept({...value,title:"Remote"});});e.controller.start(true);await e.flush();e.controller.stop();finish();await settle();expect(e.accepted).toEqual([]);expect(e.session.publishLiveProject).not.toHaveBeenCalled();expect(e.jobs.size).toBe(0);});
  it("discards a result from an earlier same-ID workspace",async()=>{const e=setup();let finish!:()=>void;vi.mocked(e.session.receiveLiveProject).mockImplementation(async(value,accept,check)=>{await new Promise<void>(resolve=>{finish=resolve;});check();accept(value);});e.controller.start(true);await e.flush();e.reset();finish();await settle();expect(e.accepted).toEqual([]);expect(e.session.publishLiveProject).not.toHaveBeenCalled();expect(e.last().mode).toBeNull();});
  it("stops on a different project and never transfers its edits",async()=>{const e=setup();e.controller.start(true);e.switchProject();await e.flush();expect(e.session.receiveLiveProject).not.toHaveBeenCalled();expect(e.last().mode).toBeNull();});
  it("rejects a late result after the account guard fails",async()=>{const e=setup();let finish!:()=>void;vi.mocked(e.session.receiveLiveProject).mockImplementation(async(value,accept,check)=>{await new Promise<void>(resolve=>{finish=resolve;});check();accept(value);});e.controller.start(true);await e.flush();e.switchAccount();finish();await settle();expect(e.accepted).toEqual([]);expect(e.session.publishLiveProject).not.toHaveBeenCalled();expect(e.last().status).toBe("error");e.controller.stop();});
  it("recaptures after a local edit arrives during a transfer",async()=>{const e=setup();let finish!:()=>void;vi.mocked(e.session.receiveLiveProject).mockImplementationOnce(async(value,accept,check)=>{await new Promise<void>(resolve=>{finish=resolve;});check();accept(value);});e.controller.start(true);await e.flush();e.edit("New local");finish();await settle();expect(e.accepted).toEqual([]);expect(e.jobs.size).toBe(1);await e.flush();expect(vi.mocked(e.session.publishLiveProject).mock.calls[0][0].title).toBe("New local");e.controller.stop();});
  it("pauses on an unknown receipt without retrying on edits or remote events",async()=>{const e=setup();vi.mocked(e.session.recoverLiveProject).mockRejectedValueOnce(new Error("Previous outcome is unknown"));e.controller.start(true);await e.flush();e.edit("More");e.controller.remote(2,2);await e.flush();expect(e.session.recoverLiveProject).toHaveBeenCalledTimes(1);expect(e.last().status).toBe("recovery");e.controller.retry();await e.flush();expect(e.session.recoverLiveProject).toHaveBeenCalledTimes(2);e.controller.stop();});
  it("preserves a conflict until retry or Stop and clears consent on reset",async()=>{const e=setup();vi.mocked(e.session.receiveLiveProject).mockRejectedValueOnce(new CloudProjectConflict("Overlap"));e.controller.start(true);await e.flush();e.edit("Private");await e.flush();expect(e.session.publishLiveProject).not.toHaveBeenCalled();expect(e.last().status).toBe("conflict");e.reset();expect(e.last().mode).toBeNull();});
  it("waits for the shared Save mutex through a completion event",async()=>{const e=setup();let finish!:()=>void,entered!:()=>void;const ready=new Promise<void>(resolve=>{entered=resolve;});const save=withCloudProjectTransfer(wallet,()=>{},async()=>{entered();await new Promise<void>(resolve=>{finish=resolve;});});await ready;vi.mocked(e.session.receiveLiveProject).mockImplementation(async()=>withCloudProjectTransfer(wallet,()=>{},async()=>undefined));e.controller.start(false);await e.flush();expect(e.last().status).toBe("waiting");expect(e.jobs.size).toBe(0);finish();await save;await settle();expect(e.jobs.size).toBe(1);await e.flush();expect(e.last().status).toBe("live");e.controller.stop();});
  it("allows one bounded reconnect and no work after Stop",async()=>{const e=setup();e.controller.start(false);await e.flush();e.controller.reconnect();await e.flush();expect(e.session.recoverLiveProject).toHaveBeenCalledTimes(2);expect(e.jobs.size).toBe(0);e.controller.stop();e.controller.reconnect();await e.flush();expect(e.session.recoverLiveProject).toHaveBeenCalledTimes(2);});
  it("starts a newly requested mode after the old in-flight transfer settles",async()=>{const e=setup();let finish!:()=>void;vi.mocked(e.session.receiveLiveProject).mockImplementationOnce(async(_value,_accept,check)=>{await new Promise<void>(resolve=>{finish=resolve;});check();});e.controller.start(true);await e.flush();e.controller.start(false);finish();await settle();expect(e.jobs.size).toBe(1);await e.flush();expect(e.session.receiveLiveProject).toHaveBeenCalledTimes(2);expect(e.session.publishLiveProject).not.toHaveBeenCalled();e.controller.stop();});
});
