project_id = "aigxuutjaqsywioxjefr"

[functions.enhance-text]
verify_jwt = false

[functions.translate-text]
verify_jwt = false

[functions.general-ai-chat]
verify_jwt = false

[functions.generate-image]
verify_jwt = false

[functions.generate-video]
verify_jwt = false

[functions.get-dhb-price]
verify_jwt = false

[functions.dehub-api]
verify_jwt = false

[functions.dehub-auth]
verify_jwt = false

[functions.get-web3auth-config]
verify_jwt = false

[functions.fetch-link-preview]
verify_jwt = false
