project_id = "aigxuutjaqsywioxjefr"

[functions.enhance-text]
verify_jwt = false

[functions.translate-text]
verify_jwt = false

[functions.general-ai-chat]
verify_jwt = false

[functions.generate-image]
verify_jwt = false
