/**
 * public/seo-i18n.json is generated by scripts/build-seo-i18n.mjs — titles
 * and descriptions from the locale files, headings and bodies from
 * scripts/seo-i18n-copy — and read by the worker at request time; the same
 * script writes the matching hreflang alternates into sitemap-static.xml.
 * Both outputs are committed rather than built, so this is what keeps them
 * honest: rebuild them here and fail when a committed copy is behind. It also
 * pins the rules the worker relies on: only the chosen languages, only ISO
 * 639-1 codes, and a language listed for a route only when the whole page is
 * translated.
 */
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { describe, expect, it } from 'vitest';
import {
  buildSeoI18n,
  SEO_I18N_LOCALES,
  SEO_I18N_ROUTES,
  withSitemapAlternates,
} from '../../scripts/build-seo-i18n.mjs';

const ROOT = resolve(__dirname, '../..');
type Row = { title: string; description: string; h1?: string; body?: string; lede?: string };
const committed = JSON.parse(readFileSync(resolve(ROOT, 'public/seo-i18n.json'), 'utf8')) as Record<
  string,
  Record<string, Row>
>;
const sitemap = readFileSync(resolve(ROOT, 'public/sitemap-static.xml'), 'utf8');

describe('seo-i18n.json', () => {
  it('matches its sources — run node scripts/build-seo-i18n.mjs after editing an SEO key or a copy file', () => {
    expect(committed).toEqual(buildSeoI18n(resolve(ROOT, 'src/i18n/locales')));
  }, 30000);

  it('covers every mapped route, and every route is a mapped one', () => {
    expect(Object.keys(committed).sort()).toEqual(Object.values(SEO_I18N_ROUTES).sort());
  });

  it('lists English plus the chosen languages only', () => {
    for (const [route, langs] of Object.entries(committed)) {
      expect(langs.en, `${route} has no English row`).toBeTruthy();
      for (const code of Object.keys(langs)) {
        expect(['en', ...SEO_I18N_LOCALES], `${route}:${code}`).toContain(code);
      }
    }
  });

  it('lists a language only with a title, description, heading and body of its own', () => {
    for (const [route, langs] of Object.entries(committed)) {
      for (const [code, t] of Object.entries(langs)) {
        if (code === 'en') continue;
        expect(t.title.trim().length, `${route}:${code} title`).toBeGreaterThan(0);
        expect(t.description.trim().length, `${route}:${code} description`).toBeGreaterThan(0);
        expect(t.h1?.trim().length, `${route}:${code} h1`).toBeGreaterThan(0);
        expect(t.body?.trim().length, `${route}:${code} body`).toBeGreaterThan(40);
        expect(t.title, `${route}:${code} title is the English one`).not.toBe(langs.en.title);
      }
    }
  });

  it('carries real bodies, not the English copy under another code', () => {
    const tv = committed['/tv'];
    const bodies = new Set(Object.values(tv).map((t) => t.body).filter(Boolean));
    expect(bodies.size).toBe(Object.keys(tv).length - 1);
    for (const [code, t] of Object.entries(tv)) {
      if (code !== 'en') expect(t.body, code).not.toContain('streams free live channels');
    }
  });

  it('serves no language on a noindex route', () => {
    expect(Object.keys(committed['/events'])).toEqual(['en']);
    expect(Object.keys(committed['/launchpad'])).toEqual(['en']);
  });
});

describe('sitemap-static.xml alternates', () => {
  it('match the table — run node scripts/build-seo-i18n.mjs', () => {
    expect(sitemap).toBe(withSitemapAlternates(sitemap, committed));
  });

  it('give every translated route a full, reciprocal set in the sitemap', () => {
    for (const [route, langs] of Object.entries(committed)) {
      const served = Object.keys(langs).filter((l) => l !== 'en');
      if (!served.length) continue;
      const bare = `https://dehub.io${route}`;
      for (const loc of [bare, ...served.map((l) => `${bare}?hl=${l}`)]) {
        const block = sitemap.match(new RegExp(`<url>\\s*<loc>${loc.replace(/[.?]/g, '\\$&')}</loc>[\\s\\S]*?</url>`));
        expect(block, loc).not.toBeNull();
        const hreflangs = [...block![0].matchAll(/hreflang="([^"]+)"/g)].map((m) => m[1]).sort();
        expect(hreflangs, loc).toEqual([...served, 'en', 'x-default'].sort());
      }
    }
  });

  it('adds nothing when run twice', () => {
    const once = withSitemapAlternates(sitemap, committed);
    expect(withSitemapAlternates(once, committed)).toBe(once);
  });
});
