
import { BlogPost as BlogPostType } from '@/types/blog';

export const tokenisedUploadsPost: BlogPostType = {
  id: 'tokenised-uploads-are-here',
  slug: 'tokenised-uploads-are-here',
  title: 'Tokenised uploads are here!',
  excerpt: 'Discover how we\'ve integrated a unique fan token experience into our app. Every upload is now a fractionalised NFT, sharing ad revenue with its owners!',
  content: `
    <h2 class="text-2xl font-bold mb-4 font-exo">Introducing a New Era of Content Monetization</h2>
    <p class="mb-4 text-lg text-royal-blue/80">How have we built in a seamless & unique fan token experience into our content app? We are incredibly excited to announce a groundbreaking feature on the DeHub platform: <strong>Tokenised Uploads</strong>!</p>
    <p class="mb-4 text-royal-blue/80">This innovation fundamentally changes how creators and fans interact with content, creating a shared economy where everyone can participate and benefit.</p>
    
    <h3 class="text-xl font-bold mt-8 mb-4 font-exo">How Tokenised Uploads Work</h3>
    <p class="mb-4 text-royal-blue/80">The magic behind this feature lies in blockchain technology, specifically with Non-Fungible Tokens (NFTs):</p>
    <ul class="list-disc list-inside space-y-3 my-4 text-royal-blue/80 pl-4">
      <li><strong>NFT Creation:</strong> Every time a creator uploads a new piece of content, it is automatically minted as an ERC-1155 NFT on the blockchain. This makes each upload a unique, verifiable digital asset.</li>
      <li><strong>Fractionalisation:</strong> Every upload's ERC1155 (NFT) now fractionalises by 1000. To make ownership accessible to everyone, these fractions act as "shares" of the content.</li>
      <li><strong>Revenue Sharing:</strong> Ad revenue generated by the content is shared evenly between each fraction. The more you keep, the more you earn. The more you sell, the more your fans earn.</li>
    </ul>

    <h3 class="text-xl font-bold mt-8 mb-4 font-exo">A Win-Win for Creators and Fans</h3>
    <p class="mb-4 text-royal-blue/80">This system creates a powerful, symbiotic relationship:</p>
    <p class="mb-4 text-royal-blue/80"><strong>For Creators:</strong> You retain initial ownership of all fractions, giving you a new way to monetize your work. You can hold onto them to earn from your own ad revenue, or sell them to your community, creating an instant income stream. The more engaged your community is, the more valuable your content fractions become.</p>
    <p class="mb-4 text-royal-blue/80"><strong>For Fans:</strong> You can now directly invest in the creators and content you love. By purchasing fractions, you're not just donating; you're acquiring a stake in the content's success. As the content generates revenue, so do you.</p>
    
    <p class="mt-8 font-semibold text-royal-blue">We believe Tokenised Uploads are the future of the creator economy. It's a system built on transparency, ownership, and shared success. Start exploring this new feature today and be a part of the revolution!</p>
  `,
  bannerImage: '/lovable-uploads/b515dd9f-ca7e-4264-a177-0ead5c2d55c6.png',
  bannerImageAlt: 'A glowing DeHub token representing tokenized uploads.',
  author: {
    name: 'DeHub Team',
  },
  publishedAt: '2023-06-10T12:00:00.000Z',
  tags: ['Tokenomics', 'NFT', 'Feature', 'Update', 'ERC1155'],
  readingTime: 3,
  featured: false,
  status: 'published',
  seoTitle: 'Tokenised Uploads: Revolutionary NFT Revenue Sharing on DeHub',
  seoDescription: 'Learn about DeHub\'s new Tokenised Uploads feature. Every upload becomes a fractionalised ERC-1155 NFT that shares ad revenue with holders, creating a new creator economy.',
};
