import { describe, expect, it, vi } from 'vitest';

// client.ts is regenerated by tooling. If a regeneration drops the relay
// fetch, users on networks that block the Supabase host lose auth and data
// with no other symptom — so pin the wiring here.
const { createClient } = vi.hoisted(() => ({ createClient: vi.fn((..._args: unknown[]) => ({})) }));
vi.mock('@supabase/supabase-js', () => ({ createClient }));

describe('Supabase client wiring', () => {
  it('hands the relay fetch to createClient', async () => {
    await import('../client');
    const { supabaseRelayFetch } = await import('../relayFetch');
    expect(createClient).toHaveBeenCalledTimes(1);
    const options = createClient.mock.calls[0][2] as { global?: { fetch?: unknown } };
    expect(options.global?.fetch).toBe(supabaseRelayFetch);
  });
});
