import "https://deno.land/x/xhr@0.1.0/mod.ts";
import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import Replicate from "https://esm.sh/replicate@0.25.2";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

interface GenerateImageRequest {
  prompt: string;
  sourceImage?: string; // Base64 data URL for editing
}

// Fallback to Replicate when Gemini blocks content
async function generateWithReplicate(prompt: string): Promise<{ imageUrl: string; text: string }> {
  const replicateApiKey = Deno.env.get('REPLICATE_API_KEY');
  if (!replicateApiKey) {
    throw new Error('REPLICATE_API_KEY not configured');
  }

  console.log('Falling back to Replicate for image generation');
  
  const replicate = new Replicate({ auth: replicateApiKey });
  
  // Use FLUX Schnell - fast and less restrictive
  const output = await replicate.run(
    "black-forest-labs/flux-schnell",
    {
      input: {
        prompt: prompt,
        go_fast: true,
        megapixels: "1",
        num_outputs: 1,
        aspect_ratio: "1:1",
        output_format: "webp",
        output_quality: 90,
        num_inference_steps: 4
      }
    }
  );

  console.log('Replicate response:', output);

  // FLUX returns an array of URLs
  const imageUrls = output as string[];
  if (!imageUrls || imageUrls.length === 0) {
    throw new Error('No image generated by Replicate');
  }

  // Fetch the image and convert to base64
  const imageResponse = await fetch(imageUrls[0]);
  const imageBlob = await imageResponse.arrayBuffer();
  const base64 = btoa(String.fromCharCode(...new Uint8Array(imageBlob)));
  const dataUrl = `data:image/webp;base64,${base64}`;

  return {
    imageUrl: dataUrl,
    text: 'Image generated with FLUX (fallback)'
  };
}

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { prompt, sourceImage } = await req.json() as GenerateImageRequest;

    if (!prompt) {
      throw new Error('Prompt is required');
    }

    const lovableApiKey = Deno.env.get('LOVABLE_API_KEY');
    if (!lovableApiKey) {
      throw new Error('LOVABLE_API_KEY not configured');
    }

    console.log('Generating image with prompt:', prompt.substring(0, 100), '| Has source image:', !!sourceImage);

    // Build messages based on whether we're editing or generating
    const messages = sourceImage ? [
      {
        role: 'user',
        content: [
          { type: 'image_url', image_url: { url: sourceImage } },
          { type: 'text', text: prompt }
        ]
      }
    ] : [
      { role: 'user', content: prompt }
    ];

    const response = await fetch('https://ai.gateway.lovable.dev/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${lovableApiKey}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: 'google/gemini-2.5-flash-image-preview',
        messages,
        modalities: ['image', 'text']
      }),
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.error('Image generation API error:', response.status, errorText);
      
      if (response.status === 429) {
        return new Response(
          JSON.stringify({ error: 'Rate limit exceeded. Please try again in a moment.' }),
          { status: 429, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
        );
      }
      if (response.status === 402) {
        return new Response(
          JSON.stringify({ error: 'AI credits exhausted. Please try again later.' }),
          { status: 402, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
        );
      }
      
      throw new Error(`Image generation failed: ${response.status}`);
    }

    const data = await response.json();
    console.log('Image generation response received');

    // Check for safety filter - if blocked, try Replicate fallback
    const finishReason = data.choices?.[0]?.native_finish_reason || data.choices?.[0]?.finish_reason;
    if (finishReason === 'IMAGE_SAFETY') {
      console.log('Gemini safety filter triggered, trying Replicate fallback');
      
      try {
        const replicateResult = await generateWithReplicate(prompt);
        return new Response(
          JSON.stringify({ 
            imageUrl: replicateResult.imageUrl, 
            text: replicateResult.text,
            success: true,
            fallback: true
          }),
          { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
        );
      } catch (replicateError) {
        console.error('Replicate fallback also failed:', replicateError);
        return new Response(
          JSON.stringify({ 
            error: 'Content was blocked and fallback generation failed. Try different wording.',
            safetyBlocked: true 
          }),
          { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
        );
      }
    }

    // Extract the generated image
    const imageUrl = data.choices?.[0]?.message?.images?.[0]?.image_url?.url;
    const textResponse = data.choices?.[0]?.message?.content || '';

    if (!imageUrl) {
      console.error('No image in response:', JSON.stringify(data).substring(0, 500));
      return new Response(
        JSON.stringify({ error: 'No image was generated. Try rephrasing your request.' }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    return new Response(
      JSON.stringify({ 
        imageUrl, 
        text: textResponse,
        success: true 
      }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  } catch (error) {
    console.error('Error in generate-image:', error);
    const errorMessage = error instanceof Error ? error.message : 'Unknown error';
    return new Response(
      JSON.stringify({ error: errorMessage }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }
});
