// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/feed.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
var MCP_URL = "https://aigxuutjaqsywioxjefr.supabase.co/functions/v1/dehub-mcp";
async function rpc(method, params) {
  const resp = await fetch(MCP_URL, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ jsonrpc: "2.0", id: 1, method, params })
  });
  const data = await resp.json();
  if (data.error) throw new Error(data.error.message ?? "DeHub MCP error");
  return data.result;
}
var feed_default = defineTool({
  name: "dehub_feed",
  title: "Get DeHub feed",
  description: "Fetch posts from the DeHub decentralized social feed.",
  inputSchema: {
    sort: z.enum(["new", "hot", "trending"]).optional().describe("Sort order"),
    category: z.string().optional().describe("Optional category filter"),
    limit: z.number().int().min(1).max(50).optional().describe("Max posts (1-50)"),
    offset: z.number().int().min(0).optional().describe("Pagination offset")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async (input) => {
    const result = await rpc("dehub_feed", input);
    return { content: [{ type: "text", text: JSON.stringify(result) }], structuredContent: result };
  }
});

// src/lib/mcp/tools/post.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
var MCP_URL2 = "https://aigxuutjaqsywioxjefr.supabase.co/functions/v1/dehub-mcp";
async function rpc2(method, params) {
  const resp = await fetch(MCP_URL2, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ jsonrpc: "2.0", id: 1, method, params })
  });
  const data = await resp.json();
  if (data.error) throw new Error(data.error.message ?? "DeHub MCP error");
  return data.result;
}
var post_default = defineTool2({
  name: "dehub_post",
  title: "Get DeHub post",
  description: "Fetch a single DeHub post by its token ID.",
  inputSchema: {
    token_id: z2.string().min(1).describe("The post's token ID")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async (input) => {
    const result = await rpc2("dehub_post", input);
    return { content: [{ type: "text", text: JSON.stringify(result) }], structuredContent: result };
  }
});

// src/lib/mcp/tools/search.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
var MCP_URL3 = "https://aigxuutjaqsywioxjefr.supabase.co/functions/v1/dehub-mcp";
async function rpc3(method, params) {
  const resp = await fetch(MCP_URL3, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ jsonrpc: "2.0", id: 1, method, params })
  });
  const data = await resp.json();
  if (data.error) throw new Error(data.error.message ?? "DeHub MCP error");
  return data.result;
}
var search_default = defineTool3({
  name: "dehub_search",
  title: "Search DeHub",
  description: "Search DeHub posts, users, and videos.",
  inputSchema: {
    query: z3.string().min(1).describe("Search query"),
    type: z3.enum(["all", "posts", "users", "videos"]).optional().describe("Result type filter"),
    limit: z3.number().int().min(1).max(50).optional().describe("Max results (1-50)")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async (input) => {
    const result = await rpc3("dehub_search", input);
    return { content: [{ type: "text", text: JSON.stringify(result) }], structuredContent: result };
  }
});

// src/lib/mcp/tools/profile.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^3.25.76";
var MCP_URL4 = "https://aigxuutjaqsywioxjefr.supabase.co/functions/v1/dehub-mcp";
async function rpc4(method, params) {
  const resp = await fetch(MCP_URL4, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ jsonrpc: "2.0", id: 1, method, params })
  });
  const data = await resp.json();
  if (data.error) throw new Error(data.error.message ?? "DeHub MCP error");
  return data.result;
}
var profile_default = defineTool4({
  name: "dehub_profile",
  title: "Get DeHub profile",
  description: "Fetch a DeHub user profile by wallet address.",
  inputSchema: {
    wallet_address: z4.string().min(1).describe("Wallet address (0x...) to look up")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async (input) => {
    const result = await rpc4("dehub_profile", input);
    return { content: [{ type: "text", text: JSON.stringify(result) }], structuredContent: result };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "dehub-mcp",
  title: "DeHub",
  version: "0.1.0",
  instructions: "Tools for DeHub \u2014 the decentralized social network. Read the public feed, fetch individual posts by token ID, search posts/users/videos, and look up user profiles by wallet address. For write actions (post, vote, comment, follow), agents register at https://dehub.io/app/agents to obtain an API key.",
  tools: [feed_default, post_default, search_default, profile_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
