// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/feed.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/tools/dehub-rpc.ts
var DEHUB_MCP_URL = "https://aigxuutjaqsywioxjefr.supabase.co/functions/v1/dehub-mcp";
function parseStreamableResponse(raw) {
  const trimmed = raw.trim();
  if (!trimmed) throw new Error("DeHub MCP returned an empty response");
  if (trimmed.startsWith("{")) return JSON.parse(trimmed);
  const dataLines = trimmed.split(/\r?\n/).filter((line) => line.startsWith("data:")).map((line) => line.slice(5).trim()).filter(Boolean);
  if (!dataLines.length) throw new Error("DeHub MCP returned no data frame");
  return JSON.parse(dataLines[dataLines.length - 1]);
}
async function callDeHubTool(name, args) {
  const response = await fetch(DEHUB_MCP_URL, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Accept: "application/json, text/event-stream"
    },
    body: JSON.stringify({
      jsonrpc: "2.0",
      id: 1,
      method: "tools/call",
      params: { name, arguments: args }
    })
  });
  if (!response.ok) {
    throw new Error(`DeHub MCP request failed with HTTP ${response.status}`);
  }
  const payload = parseStreamableResponse(await response.text());
  if (payload.error) throw new Error(payload.error.message ?? "DeHub MCP error");
  const result = payload.result;
  if (!result) throw new Error("DeHub MCP returned no result");
  const body = result.structuredContent ?? safeParse(result.content?.[0]?.text);
  if (result.isError) {
    const message = typeof body?.error === "string" ? body.error : void 0;
    throw new Error(message ?? "DeHub tool call failed");
  }
  return body ?? {};
}
function safeParse(text) {
  if (!text) return void 0;
  try {
    const parsed = JSON.parse(text);
    return parsed && typeof parsed === "object" && !Array.isArray(parsed) ? parsed : { value: parsed };
  } catch {
    return { text };
  }
}

// src/lib/mcp/tools/feed.ts
var feed_default = defineTool({
  name: "dehub_feed",
  title: "Get DeHub feed",
  description: "Fetch posts from the DeHub decentralized social feed. Returns compact post summaries \u2014 token ID, author, body and engagement counts.",
  inputSchema: {
    sort: z.enum(["new", "hot", "trending", "discussed"]).optional().describe("new = latest, hot = most liked, trending = most viewed, discussed = most commented"),
    category: z.string().optional().describe("Optional category filter"),
    search: z.string().optional().describe("Keyword to match against post titles and descriptions"),
    limit: z.number().int().min(1).max(50).optional().describe("Max posts (1-50)"),
    offset: z.number().int().min(0).optional().describe("Pagination offset")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async (input) => {
    const result = await callDeHubTool("dehub_feed", input);
    return { content: [{ type: "text", text: JSON.stringify(result) }], structuredContent: result };
  }
});

// src/lib/mcp/tools/post.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
var post_default = defineTool2({
  name: "dehub_post",
  title: "Get DeHub post",
  description: "Fetch a single DeHub post by its token ID, including author and engagement counts.",
  inputSchema: {
    token_id: z2.string().min(1).describe("The post's token ID")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async (input) => {
    const result = await callDeHubTool("dehub_post", input);
    return { content: [{ type: "text", text: JSON.stringify(result) }], structuredContent: result };
  }
});

// src/lib/mcp/tools/comments.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
var comments_default = defineTool3({
  name: "dehub_comments",
  title: "Read post comments",
  description: "Read the comment thread on a DeHub post, with author, body and like count for each comment.",
  inputSchema: {
    token_id: z3.string().min(1).describe("The post's token ID"),
    limit: z3.number().int().min(1).max(50).optional().describe("Max comments (1-50)"),
    page: z3.number().int().min(0).optional().describe("Zero-based page number")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async (input) => {
    const result = await callDeHubTool("dehub_comments", input);
    return { content: [{ type: "text", text: JSON.stringify(result) }], structuredContent: result };
  }
});

// src/lib/mcp/tools/search.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^3.25.76";
var search_default = defineTool4({
  name: "dehub_search",
  title: "Search DeHub",
  description: "Search DeHub for posts (by title and description) and people (by username and display name).",
  inputSchema: {
    query: z4.string().min(1).describe("Search query"),
    type: z4.enum(["all", "posts", "users"]).optional().describe("Restrict results to posts or users"),
    limit: z4.number().int().min(1).max(50).optional().describe("Max results per section (1-50)")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async (input) => {
    const result = await callDeHubTool("dehub_search", input);
    return { content: [{ type: "text", text: JSON.stringify(result) }], structuredContent: result };
  }
});

// src/lib/mcp/tools/profile.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z5 } from "npm:zod@^3.25.76";
var profile_default = defineTool5({
  name: "dehub_profile",
  title: "Get DeHub profile",
  description: "Fetch a DeHub user profile by wallet address or username.",
  inputSchema: {
    user: z5.string().min(1).describe("Wallet address (0x...) or username to look up")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async (input) => {
    const result = await callDeHubTool("dehub_profile", input);
    return { content: [{ type: "text", text: JSON.stringify(result) }], structuredContent: result };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "dehub-mcp",
  title: "DeHub",
  version: "0.2.0",
  instructions: "Read-only tools for DeHub \u2014 the decentralized social network. Browse the feed, fetch a post by token ID, read a post's comments, search posts and people, and look up profiles by wallet address or username. This connector cannot write. To let an agent post, vote, comment or follow, create an agent at https://dehub.io/app/agents and add its personal connector URL instead \u2014 it carries the agent's key in the URL and exposes the write tools as well.",
  tools: [feed_default, post_default, comments_default, search_default, profile_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
