-- Stage reminders + short share ids
-- =================================
-- Two things every stage announcement was missing:
--
-- 1. `short_id` — a dense sequential integer so a share link can read
--    /stages/7 instead of /stage/<uuid>. GENERATED BY DEFAULT (not ALWAYS)
--    so a backfill or restore can still write explicit values. Existing rows
--    are renumbered by age so the numbering is stable from day one.
--
-- 2. `stage_reminders` — one row per (stage, wallet): "tell me when this
--    starts". Delivery is entirely server-side, riding the existing
--    custom_notifications table the web notification tabs already read:
--      · a trigger fans notifications out the moment the host flips the row
--        scheduled → live (the moment that actually matters — stages rarely
--        start on the advertised minute);
--      · a pg_cron pass (scheduled separately, see the note at the bottom)
--        catches "starting soon" ten minutes before scheduled_at.
--
-- RLS mirrors the neighbouring stage tables: open SELECT/INSERT (the plain
-- client sends no wallet header — see StageContext), DELETE gated on
-- get_request_wallet_address() like the audio_spaces delete, which the
-- un-remind call site satisfies with an explicit .setHeader.

ALTER TABLE public.audio_spaces
  ADD COLUMN short_id integer GENERATED BY DEFAULT AS IDENTITY;

WITH ordered AS (
  SELECT id, row_number() OVER (ORDER BY created_at, id) AS rn
  FROM public.audio_spaces
)
UPDATE public.audio_spaces a
SET short_id = o.rn
FROM ordered o
WHERE a.id = o.id;

-- The third argument matters on an empty table: two-arg setval marks the value
-- as already used, so the first stage would come out as 2 and /stages/1 would
-- never exist. is_called = false when there is nothing to renumber.
SELECT setval(
  pg_get_serial_sequence('public.audio_spaces', 'short_id'),
  GREATEST((SELECT COALESCE(max(short_id), 0) FROM public.audio_spaces), 1),
  EXISTS (SELECT 1 FROM public.audio_spaces)
);

ALTER TABLE public.audio_spaces
  ADD CONSTRAINT audio_spaces_short_id_key UNIQUE (short_id);

CREATE TABLE public.stage_reminders (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  space_id uuid NOT NULL REFERENCES public.audio_spaces(id) ON DELETE CASCADE,
  wallet_address text NOT NULL,
  -- Stamped by the pre-start cron pass so each reminder fires at most once.
  pre_start_notified_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (space_id, wallet_address)
);

CREATE INDEX idx_stage_reminders_space ON public.stage_reminders(space_id);

ALTER TABLE public.stage_reminders ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can view stage reminders"
ON public.stage_reminders
FOR SELECT
USING (true);

CREATE POLICY "Authenticated users can set reminders"
ON public.stage_reminders
FOR INSERT
WITH CHECK (true);

CREATE POLICY "Users can remove their own reminder"
ON public.stage_reminders
FOR DELETE
USING (lower(wallet_address) = get_request_wallet_address());

-- The host started the stage: tell everyone who asked. The host is excluded —
-- they are the one who pressed the button. content stays '' because the
-- notification UI composes the sentence from type + reference_title, the same
-- convention feature_request_like already follows. reference_id prefers the
-- short id so the notification click lands on the short link.
CREATE OR REPLACE FUNCTION public.notify_stage_reminders_live()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO custom_notifications
    (recipient_address, actor_address, actor_username, actor_avatar, type, content, reference_id, reference_title)
  SELECT
    r.wallet_address,
    NEW.host_wallet_address,
    NEW.host_username,
    NEW.host_avatar,
    'stage_live',
    '',
    COALESCE(NEW.short_id::text, NEW.id::text),
    NEW.title
  FROM stage_reminders r
  WHERE r.space_id = NEW.id
    AND lower(r.wallet_address) <> lower(NEW.host_wallet_address);
  RETURN NEW;
END;
$$;

CREATE TRIGGER tr_stage_reminders_live
AFTER UPDATE ON public.audio_spaces
FOR EACH ROW
WHEN (OLD.status = 'scheduled' AND NEW.status = 'live')
EXECUTE FUNCTION public.notify_stage_reminders_live();

-- Pre-start pass, scheduled OUTSIDE this migration because cron.schedule is a
-- runtime call, not schema (run once against prod alongside applying this
-- file; pg_cron is installed there). The host is NOT excluded here — a host
-- who set a reminder on their own stage wants the nudge most. The 30-minute
-- lower bound stops a long-overdue stage from greeting a late reminder with
-- a stale "starting soon".
--
-- SELECT cron.schedule('stage-reminders-prestart', '* * * * *', $job$
--   WITH due AS (
--     UPDATE stage_reminders r SET pre_start_notified_at = now()
--     FROM audio_spaces s
--     WHERE s.id = r.space_id
--       AND r.pre_start_notified_at IS NULL
--       AND s.status = 'scheduled'
--       AND s.scheduled_at <= now() + interval '10 minutes'
--       AND s.scheduled_at >  now() - interval '30 minutes'
--     RETURNING r.wallet_address, s.host_wallet_address, s.host_username,
--               s.host_avatar, s.title, s.short_id, s.id AS space_uuid
--   )
--   INSERT INTO custom_notifications
--     (recipient_address, actor_address, actor_username, actor_avatar, type, content, reference_id, reference_title)
--   SELECT wallet_address, host_wallet_address, host_username, host_avatar,
--          'stage_reminder', '', COALESCE(short_id::text, space_uuid::text), title
--   FROM due;
-- $job$);
